# Generated by Django 4.1 on 2024-09-14 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_alter_interview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 14, 9, 55, 27, 717566, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
